name: Mirroring

on: [push, workflow_dispatch]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
          TARGET_REPO_URL: git@github.com:pssingh21/test-repo-mirror.git
        run: |
          set -eu
          mkdir -p ~/.ssh
          echo "${{ env.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          export GIT_SSH_COMMAND="ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -l git"
          git remote add mirror "${{ env.TARGET_REPO_URL }}"
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
          git remote remove "mirror"
      
#       - uses: pixta-dev/repository-mirroring-action@v1
#         with:
#           target_repo_url:
#             git@github.com:pssingh21/test-repo-mirror.git
#           ssh_private_key:                              # <-- use 'secrets' to pass credential information.
#             ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
